name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.2

  firebase_core: ^3.7.0

  image_picker: 1.1.2

  # Cupertino icons for iOS
  cupertino_icons: ^1.0.8

  # HTTP package to handle network requests
  # Use latest stable version if available

  # State management package
  provider: ^6.0.5

  # For form validation and handling
  flutter_form_builder: ^7.5.0

  # For JSON serialization/deserialization
  json_serializable: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.0 # Updated version for compatibility with json_serializable

flutter:
  uses-material-design: true
